version: '3.4'

services:
    aerospikedb:
        image: aerospike/aerospike-server:latest
        networks:
        - aerospikenetwork
        labels:
            com.aerospike.description: "This label is for all containers for the Aerospike service"
        command: [ "--config-file","/run/secrets/aerospike.conf"]
        volumes:
        - ./data:/opt/aerospike/data/
        secrets:
        - source: conffile
          target: aerospike.conf
#          mode: 0440
    
    meshworker:
        image: aerospike/aerospike-tools:3.15.0.3
        networks:
        - aerospikenetwork
        depends_on:
        - aerospikedb
        entrypoint:
        - /run/secrets/discovery
        - "--servicename"
        - aerospikedb
        - "-i"
        - "5"
        - "-v"
        secrets:
        - source: discoveryfile
          target: discovery
#          mode: 0750

networks:
  aerospikenetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.123.0/24

secrets:
    conffile:
        file: ./aerospike.conf
    discoveryfile:
        file: ./discovery.py
